version: 2.1
orbs:
  node: circleci/node@4.3.0
executors:
  node:
    docker:
      - image: cimg/node:16.1.0

# comment
jobs:
  tsc:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: tsc

  lint:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn posttest

workflows:
  version: 2.1
  test:
    jobs:
      - lint
      - tsc
