version: 2.1
orbs:
  node: circleci/node@4.3.0
executors:
  node:
    docker:
      - image: cimg/node:20.18.0

jobs:
  build:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run prepack

  lint:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run posttest

workflows:
  version: 2.1
  test:
    jobs:
      - lint
      - build
